# ===============================
# SERVER CONFIGURATION
# ===============================
spring.application.name=api
server.port=8080

# ===============================
# FILE UPLOAD CONFIGURATION
# ===============================
# Allows users to upload ZIP files up to 100MB (Adjust if needed)
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB


# ===============================
# GITHUB OAUTH2 CONFIGURATION
# ===============================
spring.security.oauth2.client.registration.github.client-id=Ov23liux5ltFo6i6fTJI
spring.security.oauth2.client.registration.github.client-secret=9b9bfedd8fa66267741e70f7e5991f522c402249
spring.security.oauth2.client.registration.github.scope=read:user, repo